### PR TITLE
Revert swift version changes

### PR DESCRIPTION
**Pull request by dmbryson**
Swift-CI broke with these changes.  Seems the verison check is not being
re-run after the initial configure step.

rdar://problem/52198587

### CODE REVIEW

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by aciidb0mb3r** [comment]
When was this introduced?

**Comment by dmbryson** [comment]
Introduced in #477 cc: @compnerd

**Comment by dmbryson** [comment]
Hmm, odd linux failure: ```/home/buildnode/jenkins/workspace/swift-llbuild-PR-Linux-smoke-test/swift-corelibs-libdispatch/src/swift/Block.swift:14:8: error: no such module '_SwiftDispatchOverlayShims'``` cc @shahmishal

**Comment by aciidb0mb3r** [comment]
@swift-ci smoke test linux

**Comment by aciidb0mb3r** [comment]
@dmbryson ignore that, it's the super flaky module cache issue: <rdar://problem/48443680>

**Comment by dmbryson** [comment]
Yay for flaky build issues!  😉

**Comment by compnerd** [comment]
This seems to break the windows build :-( https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=3622&view=logs&j=b9e62f99-1a98-5ed7-01d2-f4794231ed79

**Comment by compnerd** [comment]
@dmbryson - there seems to be some miscommunication here.  @jakepetroules doesn't want this to run every time, you want this to run every time.  I really don't care (and would rather that it never ran).  Can we get this sorted out please?  This is the only change that is needed to ensure that we can get this building in CI for WIndows.

**Comment by dmbryson** [comment]
Sorry, I missed the other discussion.  My understanding is that the primary reason this needs to run every time is that in some Swift-CI pipelines where things are bootstrapped, we end up building llbuild more than once with different swift compiler versions.  If we don't check each build, the subsequent passes fail because of module version mismatches.

**Comment by dmbryson** [comment]
i.e. from the referenced radar: https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-14_04/7621 

```
-- Using provided swiftc: /home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-14_04/buildbot_incremental/swift-linux-x86_64/bin/swiftc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-14_04/buildbot_incremental/llbuild-linux-x86_64
+ popd
~/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-14_04
+ /opt/bin//cmake --build /home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-14_04/buildbot_incremental/llbuild-linux-x86_64 -- -j4 all
ninja: no work to do.

---------------

Ninja shouldn't say there is no work to do. It should say something like "[1/3] Checking Swift compiler version".

This is probably fallout from all the CMake changes that went in recently.
```

**Comment by aciidb0mb3r** [comment]
Explained the problem to @compnerd on Slack. He's trying to figure out if we can express dependency on the swift compiler using CMake, otherwise we can convert the script to Python.
